graph LR
  AppModule-->TranslatorModule
  TranslatorModule-->HostModule
  TranslatorModule-->EditorModule
  TranslatorModule-->CommandModule
  CommandModule-->HostModule
  CommandModule-->EditorModule
  CommandModule-->RecreatorModule
  CommandModule-->PreRunModule
  PreRunModule-->ErrorModule
  ErrorModule-->HostModule
  CommandModule-->RuntimeModule
  RuntimeModule-->HostModule
  RuntimeModule-->InterruptModule
  RuntimeModule-->ErrorModule
